wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=<empty>
     - VIRTUAL_HOST=www.kudosdata.com
    ports:
     - "127.0.0.1:8081:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html
     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=<empty>
     - MYSQL_DATABASE=<empty>
    volumes:
     - ./database:/var/lib/mysql
nginx:
   image: jwilder/nginx-proxy
   ports:
     - 80:80
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro

